CREATE TABLE USER_INFO
(
user_id int generated by default as identity primary key,
first_name varchar(20) not null,
last_name varchar(20) not null,
email varchar(35) not null,
phone varchar(11) not null,
user_password varchar(100) not null,
date_of_birth date not null,
gender varchar(10) not null,
city varchar(35) not null,
street varchar(35) not null,
home varchar(20) not null,
flat varchar(10) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)
///mkr
INSERT ALL 
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(11 , 'inna' ,'anatolieva','soulgros@mail.ru','87078764562','soulgros123qwerty', TO_DATE('2003/03/07','yyyy/mm/dd'), 'female' , 'Almaty' , 'Sefulina' , '510a' , '5' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(12 , 'sanya' ,'temirbekova','sanyasha@bk.ru','87075436472','123456789qwerty', TO_DATE('2000/01/11','yyyy/mm/dd'), 'female' , 'Almaty' , 'Shevchenko' , '99' , '4' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(13 , 'talap' ,'akashew','user_talap@mail.ru','87710989213','thatisverystrongpass231', TO_DATE('2001/03/26','yyyy/mm/dd'), 'male' , 'Alamty' , 'Baytursinova' , '97' , '16' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(14 , 'serik' ,'jerebaev','serikovvv@mail.ru','87080082456','iro3e2oi3ijro', TO_DATE('2000/04/08','yyyy/mm/dd'), 'male' , 'Alamty' , 'Abaya' , '42' , '7' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(15 , 'berik' ,'aydarov','bereke234@mail.ru','87470989874','berikberki4393', TO_DATE('1999/08/01','yyyy/mm/dd'), 'male' , 'Almaty' , 'Buhar Jirau' , '27/5 blok 3' , '43' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(16 , 'bahtiyar' ,'ulasbekov','baha_01@bk.ru','87772546733','ulas98989ulas', TO_DATE('2005/04/27','yyyy/mm/dd'), 'male' , 'Almaty' , 'Abaya' , '60' , '5' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(17 , 'dasha' ,'evgenieva','dasha_323@mail.ru','87715434521','viiids2213', TO_DATE('2007/06/02','yyyy/mm/dd'), 'female' , 'Alamty' , 'Utepova' , '3/1' , '2' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(18 , 'nikolai' ,'samaletin','samaletik228@mail.ru','87779299384','19930406', TO_DATE('2002/02/14','yyyy/mm/dd'), 'male' , 'Alamty' , 'Rozabokieva' , '145' , '77' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(19 , 'aslan' ,'ibragimov','ibragim777@mail.ru','87074453498','asp342aspan', TO_DATE('2003/10/29','yyyy/mm/dd'), 'male' , 'Almaty' , 'Solnechnaya' , '31' , '13' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_INFO(user_id , first_name , last_name , email , phone , user_password  ,date_of_birth , gender, city , street ,home , flat , create_user , update_user , create_time , update_time)
VALUES(20 , 'adema' ,'kudaibergenova','ta_samaya_adema@bk.ru','87714432678','ademalieva7766', TO_DATE('2001/12/03','yyyy/mm/dd'), 'female' , 'Almaty' , 'Taugul' , '46' , '65' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE ORDER_STATUS
(
order_status_id int generated by default as identity primary key,
status varchar(20) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(86,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(87,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(88,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(89,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(90,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(91,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(92,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(93,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(94,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(95,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(96,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(97,'processing','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(98,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(99,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO ORDER_STATUS(order_status_id , status , create_user , update_user , create_time , update_time)
VALUES(100,'completed','ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'),TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE USER_ORDER
(
order_id int generated by default as identity primary key,
USER_INFO int references USER_INFO(user_id),
ORDER_STATUS int references ORDER_STATUS(order_status_id),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)
 
SELECT USER_INFO , COUNT(USER_INFO) FROM USER_ORDER
GROUP BY USER_INFO
ORDER BY COUNT(USER_INFO) DESC;

SELECT order_status_id FROM ORDER_STATUS WHERE status = 'completed';
SELECT order_status_id FROM ORDER_STATUS WHERE status = 'processing';

SELECT order_id, status FROM USER_ORDER INNER JOIN ORDER_STATUS ON USER_ORDER.order_id = ORDER_STATUS.order_status_id WHERE status = 'completed';

SELECT USER_ORDER , item_price FROM USER_DELIVARY WHERE item_price > 10000;

SELECT AVG(item_price) AS "Avg_Item" FROM USER_DELIVARY WHERE item_price > AVG(item) GROUP BY order_id;

SELECT delivary_id , AVG(DISTINCT item_price) AS "price more than avg" FROM USER_DELIVARY WHERE item_price > 18000 GROUP BY delivary_id;

CREATE OR REPLACE PROCEDURE create_order(get_order_id int,get_order_status int,get_user_id int, get_create_user varchar, get_create_date date)
AS
BEGIN
INSERT INTO USER_ORDER(order_id , ORDER_STATUS ,USER_INFO, create_user , update_user , create_time , update_time)
VALUES (get_order_id,get_order_status,get_user_id,get_create_user,get_create_user,get_create_date,get_create_date);
END;

EXECUTE create_order(101,101,6,'ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'));

SELECT PRODUCT_INFO , COUNT(PRODUCT_INFO) FROM USER_ORDER_PRODUCT
GROUP BY PRODUCT_INFO ORDER BY COUNT(PRODUCT_INFO) DESC;



INSERT ALL 
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(91,5,91,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(92,4,92,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(93,3,93,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(94,1,94,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(95,6,95,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(96,8,96,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(97,9,97,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(98,6,98,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(99,15,99,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO USER_ORDER(order_id,USER_INFO,ORDER_STATUS,create_user,update_user,create_time,update_time)
VALUES
(100,12,100,'ADMIN','ADMIN',TO_DATE(SYSDATE,'YYYY-MM-DD'),TO_DATE(SYSDATE,'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

--ENTITY

CREATE TABLE USER_DELIVARY
(
delivary_id int generated by default as identity primary key,
USER_ORDER int references USER_ORDER(order_id),
item_price number(10) not null,
delivary_price number(10) not null,
distance number(5) not null,
send_time date not null,
arrived_time date not null,
city varchar(35) not null,
home varchar(20) not null,
street varchar(35) not null,
flat varchar(20) not null,
delivary_type varchar(25) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL 
INTO USER_DELIVARY(delivary_id , USER_ORDER , item_price  , delivary_price , distance , send_time , arrived_time , city , home , street , flat , delivary_type , create_user , update_user , create_time , update_time)
VALUES
(7, 7, 9000 , 1000 , 2300 , TO_DATE('2024/06/21' , 'YYYY-MM-DD') , TO_DATE('2024/06/22', 'YYYY-MM-DD'), 'Almaty', 'Saina 34' , 'Saina' , '3' , 'car' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_DELIVARY(delivary_id , USER_ORDER , item_price  , delivary_price , distance , send_time , arrived_time , city , home , street , flat , delivary_type , create_user , update_user , create_time , update_time)
VALUES
(8, 8, 15000 , 1500 , 3100 , TO_DATE('2024/07/01' , 'YYYY-MM-DD') , TO_DATE('2024/07/03', 'YYYY-MM-DD'), 'Almaty', 'Shalapina 12' , 'Shalapina' , '54' , 'car' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_DELIVARY(delivary_id , USER_ORDER , item_price  , delivary_price , distance , send_time , arrived_time , city , home , street , flat , delivary_type , create_user , update_user , create_time , update_time)
VALUES
(9, 9, 4000 , 500 , 1400 , TO_DATE('2024/07/02' , 'YYYY-MM-DD') , TO_DATE('2024/07/04', 'YYYY-MM-DD'), 'Almaty', 'Joldasbekova' , 'Joldasbekova 22' , '7' , 'walking' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

INSERT 
INTO USER_DELIVARY(delivary_id , USER_ORDER , item_price  , delivary_price , distance , send_time , arrived_time , city , home , street , flat , delivary_type , create_user , update_user , create_time , update_time)
VALUES
(10, 10, 19000 , 6000 , 2500 , TO_DATE('2024/06/30' , 'YYYY-MM-DD') , TO_DATE('2024/07/01', 'YYYY-MM-DD'), 'Almaty', 'Aksay-1 324/a' , 'Rayinbek batyr' , '11' , 'car' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'));



CREATE TABLE TRANSACTION_STATUS
(
transaction_status_id int generated by default as identity primary key,
status varchar(20),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL 
INTO TRANSACTION_STATUS (transaction_status_id , status , create_user , update_user , create_time , update_time)
VALUES (6, 'rejected' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION_STATUS (transaction_status_id , status , create_user , update_user , create_time , update_time)
VALUES (7, 'completed' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION_STATUS (transaction_status_id , status , create_user , update_user , create_time , update_time)
VALUES (8, 'completed' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION_STATUS (transaction_status_id , status , create_user , update_user , create_time , update_time)
VALUES (9, 'waiting' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION_STATUS (transaction_status_id , status , create_user , update_user , create_time , update_time)
VALUES (10, 'completed' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;


CREATE TABLE TRANSACTION
(
transaction_id int generated by default as identity primary key,
TRANSACTION_STATUS int references TRANSACTION_STATUS(transaction_status_id),
USER_ORDER int references USER_ORDER(order_id),
transaction_time date not null,
transaction_method varchar(20) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL
INTO TRANSACTION (transaction_id , TRANSACTION_STATUS , USER_ORDER , transaction_time , transaction_method , create_user , update_user , create_time , update_time)
VALUES (6 , 6 , 6 , TO_DATE('2024/06/29', 'YYYY-MM-DD') , 'KASPI GOLD' , 'ADMIN', 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION (transaction_id , TRANSACTION_STATUS , USER_ORDER , transaction_time , transaction_method , create_user , update_user , create_time , update_time)
VALUES (7 , 7 , 7 , TO_DATE('2024/06/21', 'YYYY-MM-DD') , 'KASPI GOLD' , 'ADMIN', 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION (transaction_id , TRANSACTION_STATUS , USER_ORDER , transaction_time , transaction_method , create_user , update_user , create_time , update_time)
VALUES (8 , 8 , 8 , TO_DATE('2024/07/01', 'YYYY-MM-DD') , 'HALYK BANK' , 'ADMIN', 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION (transaction_id , TRANSACTION_STATUS , USER_ORDER , transaction_time , transaction_method , create_user , update_user , create_time , update_time)
VALUES (9 , 9 , 9 , TO_DATE('2024/07/02', 'YYYY-MM-DD') , 'HALYK BANK' , 'ADMIN', 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO TRANSACTION (transaction_id , TRANSACTION_STATUS , USER_ORDER , transaction_time , transaction_method , create_user , update_user , create_time , update_time)
VALUES (10 , 10 , 10 , TO_DATE('2024/06/30', 'YYYY-MM-DD') , 'FORTE BANK' , 'ADMIN', 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE PRODUCT_STATUS
(
product_status_id int generated by default as identity primary key,
status varchar(20) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL 
INTO PRODUCT_STATUS (product_status_id , status , create_user , update_user , create_time , update_time)
VALUES (6,'prepared' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_STATUS (product_status_id , status , create_user , update_user , create_time , update_time)
VALUES (7,'ready' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_STATUS (product_status_id , status , create_user , update_user , create_time , update_time)
VALUES (8,'ready' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_STATUS (product_status_id , status , create_user , update_user , create_time , update_time)
VALUES (9,'ready' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_STATUS (product_status_id , status , create_user , update_user , create_time , update_time)
VALUES (10,'ready' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;


CREATE TABLE PRODUCT_INFO
(
product_id int generated by default as identity primary  key,
PRODUCT_STATUS int references PRODUCT_STATUS(product_status_id),
price number(10) not null,
product_count number(5) not null,
weight float(5) not null,
product_size varchar(20) not null,
in_stock varchar(20) not null,
producer_country varchar(35) not null,
product_name varchar(35) not null,
product_type varchar(35) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE PRODUCT_INFO RENAME COLUMN cout TO product_count;
ALTER TABLE PRODUCT_INFO MODIFY weight float(5);
DROP TABLE PRODUCT_INFO;

INSERT ALL 
INTO PRODUCT_INFO (product_id , PRODUCT_STATUS , price , product_count , weight , product_size , in_stock , producer_country , product_name , product_type , create_user ,  update_user ,  create_time , update_time )
VALUES (6 , 6 , 3500 , 234 , 220 , 'big', 'composition' , 'German' ,'spar' , 'car_detail' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_INFO (product_id , PRODUCT_STATUS , price , product_count , weight , product_size , in_stock , producer_country , product_name , product_type , create_user ,  update_user ,  create_time , update_time )
VALUES (7 , 7 , 500 , 3248 , 0.1 , 'small', 'composition' , 'China' ,'freshener' , 'car_accesuar' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_INFO (product_id , PRODUCT_STATUS , price , product_count , weight , product_size , in_stock , producer_country , product_name , product_type , create_user ,  update_user ,  create_time , update_time )
VALUES (8 , 8 , 15000 , 519 ,  0.6 , 'medium', 'composition' , 'German' ,'case' , 'car_accesuar' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_INFO (product_id , PRODUCT_STATUS , price , product_count , weight , product_size , in_stock , producer_country , product_name , product_type , create_user ,  update_user ,  create_time , update_time )
VALUES (9 , 9 , 7500 , 909 , 0.3 , 'small', 'composition' , 'Jpan' , 'timing belt' , 'car_detail' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO PRODUCT_INFO (product_id , PRODUCT_STATUS , price , product_count , weight , product_size , in_stock , producer_country , product_name , product_type , create_user ,  update_user ,  create_time , update_time )
VALUES (10 , 10 , 45000 , 44 , 25.5 , 'big', 'composition' , 'Jpan' , 'door' , 'car_detail' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE USER_ORDER_PRODUCT
(
order_product_id int generated by default as identity primary key,
USER_ORDER int references USER_ORDER(order_id),
PRODUCT_INFO int references PRODUCT_INFO(product_id),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL 
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (180 , 96 , 3 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (181 , 96 , 7 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (182 , 97 , 2 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (183 , 97 , 3 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (184 , 98 , 4 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (185 , 99 , 7 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (186 , 99 , 7 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO USER_ORDER_PRODUCT(order_product_id , USER_ORDER , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES (187 , 100 , 10 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL; 

CREATE TABLE COMPOSITION_INFO
(
composition_id int generated by default as identity primary key,
composition_capacity number(10) not null,
micro_district varchar(35) not null,
shipment date not null,
composition_name varchar(20) not null,
create_user varchar(20) not null,
update_user varchar(20) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE COMPOSITION_INFO RENAME COLUMN micro_districts TO micro_district;

INSERT ALL
INTO COMPOSITION_INFO (composition_id , composition_capacity , micro_district ,  composition_name  , shipment , create_user , update_user ,create_time , update_time)
VALUES (2, 30000 , 'JETISU-3' , 'COM-01' , TO_DATE('2024/07/07' , 'YYYY-MM-DD') , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION_INFO (composition_id , composition_capacity , micro_district ,  composition_name  , shipment , create_user , update_user ,create_time , update_time)
VALUES (3, 25000 , 'AKSAY-4' , 'COM-05' , TO_DATE('2024/07/07' , 'YYYY-MM-DD') , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE COMPOSITION__PRODUCT
(
composition_product_id int generated by default as identity primary key,
COMPOSITION_INFO int references COMPOSITION_INFO(composition_id),
PRODUCT_INFO int references PRODUCT_INFO(product_id),
create_user varchar(20) not null,
update_user varchar(20) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE COMPOSITION__PRODUCT RENAME COLUMN COMPOSITION__PRODUCT_id TO composition_product_id;

INSERT ALL 
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(1, 1 , 6, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(2, 1 , 10, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(3, 3 , 1, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(4, 3 , 2, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(5, 3 , 3, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(6, 3 , 4, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(7, 3 , 5, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(8, 3 , 7, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(9, 2 , 8, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO COMPOSITION__PRODUCT(composition_product_id , COMPOSITION_INFO , PRODUCT_INFO , create_user , update_user , create_time , update_time)
VALUES(10, 2 , 9, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE SERVICE_INFO
(
service_id int generated by default as identity primary key,
price number(10) not null,
service_type varchar(20),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE SERVICE_INFO DROP COLUMN end_time;

INSERT ALL
INTO SERVICE_INFO(service_id , price , service_type , create_user , update_user , create_time , update_time)
VALUES(4, 25000 , 'repair' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO SERVICE_INFO(service_id , price , service_type , create_user , update_user , create_time , update_time)
VALUES(5, 75000 , 'repair-rplace' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE,'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE USER_ORDER_SERVICE
(
order_service_id int generated by default as identity primary key,
USER_ORDER int references USER_ORDER(order_id),
SERVICE_INFO int references SERVICE_INFO(service_id),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE USER_ORDER_SERVICE RENAME COLUMN tabler_service TO SERVICE_INFO;

INSERT ALL
INTO USER_ORDER_SERVICE (order_service_id, USER_ORDER , SERVICE_INFO , create_user , update_user , create_time , update_time)
VALUES(9, 10 , 8 , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL; 


CREATE TABLE EMPLOYEE _INFO
(
employee_id int generated by default as identity primary key,
date_of_birth date not null,
first_name varchar(20) not null,
last_name varchar(20) not null,
email varchar(35) not null,
specialty varchar(25) not null,
phone varchar(11) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL
INTO EMPLOYEE _INFO(employee_id , first_name , last_name , date_of_birth , email , specialty , phone , create_user , update_user , create_time , update_time)
VALUES (7, 'Erimhan' , 'Serikov' , TO_DATE('1985/10/04','yyyy/mm/dd') , 'AnatoleV@mail.ru' , 'car-repair' , '87472347651', 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE _INFO(employee_id , first_name , last_name , date_of_birth , email , specialty , phone , create_user , update_user , create_time , update_time)
VALUES (8, 'Sayat' , 'Saparov' , TO_DATE('1987/04/19', 'yyyy/mm/dd') , 'CreedE@mail.ru' , 'car-repair' , '87472347651', 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE _INFO(employee_id , first_name , last_name , date_of_birth , email , specialty , phone , create_user , update_user , create_time , update_time)
VALUES (9, 'Daulte' , 'Jandosov' , TO_DATE('2003/08/24', 'yyyy/mm/dd') , 'SashaSem@mail.ru' , 'car-washing' , '87472347651', 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE SERVICE_EMPLOYEE
(
service_employee_id int generated by default as identity primary key,
EMPLOYEE _INFOint references ENTITY_employee(employee_id),
SERVICE_INFO int references SERVICE_INFO(service_id),
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)


INSERT ALL 
INTO SERVICE_EMPLOYEE(service_employee_id , EMPLOYEE _INFO, SERVICE_INFO , create_user , update_user , create_time , update_time)
VALUES(24, 9 , 1, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE,'YYYY-MM-DD'))
INTO SERVICE_EMPLOYEE(service_employee_id , EMPLOYEE _INFO, SERVICE_INFO , create_user , update_user , create_time , update_time)
VALUES(25, 9 , 3, 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE,'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE DIRECTOR_INFO
(
director_id int generated by default as identity primary key,
date_of_birth date not null,
fist_name varchar(20) not null,
last_name varchar(20) not null,
phone varchar(11) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

ALTER TABLE DIRECTOR_INFO RENAME COLUMN fist_name to first_name;

INSERT ALL 
INTO DIRECTOR_INFO(director_id , date_of_birth , first_name , last_name , phone , create_user , update_user , create_time , update_time)
VALUES(1,TO_DATE('1990/07/24','YYYY-MM-DD'), 'Dias', 'Badanbaev' , '87771232765' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO DIRECTOR_INFO(director_id , date_of_birth , first_name , last_name , phone , create_user , update_user , create_time , update_time)
VALUES(2,TO_DATE('1988/01/08','YYYY-MM-DD'), 'Erlan', 'Usepov' , '87011112122' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE,'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE OFFICE_INFO
(
office_id int generated by default as identity primary key,
micro_districts varchar(50) not null,
office_name varchar(35) not null,
create_user varchar(50) not null,
update_user varchar(50) not null,
create_time date not null,
update_time date not null
)

INSERT ALL 
INTO OFFICE_INFO(office_id , office_name , micro_districts , create_user , update_user , create_time , update_time)
VALUES(1, 'ALAMA' , 'SAMAL-3' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO OFFICE_INFO(office_id , office_name , micro_districts , create_user , update_user , create_time , update_time)
VALUES(2, 'ALAMA-GROUP' , 'KOKTEM-2' , 'ADMIN' , 'ADMIN' , TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

CREATE TABLE DIRECTOR_INFO_OFFICE
(
_id int generated by default as identity primary key,
DIRECTOR_INFO int references DIRECTOR_INFO(director_id),
OFFICE_INFO int references  OFFICE_INFO(office_id),
crate_user varchar(50) not null,
update_user varchar(50) not null,
crete_time date not null,
update_ime date not null
)

ALTER TABLE DIRECTOR_INFO_OFFICE RENAME COLUMN crate_user to create_user;
ALTER TABLE DIRECTOR_INFO_OFFICE RENAME COLUMN crete_time to create_time;
ALTER TABLE DIRECTOR_INFO_OFFICE RENAME COLUMN update_ime to update_time;

INSERT ALL
INTO DIRECTOR_INFO_OFFICE(_id, DIRECTOR_INFO , OFFICE_INFO , create_user , update_user , create_time , update_time)
VALUES (1,1,1,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO DIRECTOR_INFO_OFFICE(_id, DIRECTOR_INFO , OFFICE_INFO , create_user , update_user , create_time , update_time)
VALUES (2,2,2,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD') , TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;


DROP DIRECTOR_INFO_OFFICE;

CREATE TABLE EMPLOYEE_OFFICE
(
employee_office_id int generated by default as identity primary key,
OFFICE_INFO int references OFFICE_INFO(office_id),
EMPLOYEE _INFOint references ENTITY_employee(employee_id),
create_user varchar(20) not null,
update_user varchar(20) not null,
create_time date not null,
update_time date not null
)

DROP TABLE EMPLOYEE_OFFICE;

INSERT ALL 
INTO EMPLOYEE_OFFICE(employee_office_id , OFFICE_INFO , EMPLOYEE _INFO, create_user , update_user , create_time , update_time)
VALUES(5,2,8,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE_OFFICE(employee_office_id , OFFICE_INFO , EMPLOYEE _INFO, create_user , update_user , create_time , update_time)
VALUES(6,2,4,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE_OFFICE(employee_office_id , OFFICE_INFO , EMPLOYEE _INFO, create_user , update_user , create_time , update_time)
VALUES(7,2,5,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE_OFFICE(employee_office_id , OFFICE_INFO , EMPLOYEE _INFO, create_user , update_user , create_time , update_time)
VALUES(8,2,9,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
INTO EMPLOYEE_OFFICE(employee_office_id , OFFICE_INFO , EMPLOYEE _INFO, create_user , update_user , create_time , update_time)
VALUES(9,2,6,'ADMIN','ADMIN',TO_DATE(SYSDATE, 'YYYY-MM-DD'), TO_DATE(SYSDATE, 'YYYY-MM-DD'))
SELECT 1 FROM DUAL;

SELECT PRODUCT_INFO , COUNT(PRODUCT_INFO) FROM USER_ORDER_PRODUCT
GROUP BY PRODUCT_INFO ORDER BY COUNT(PRODUCT_INFO) DESC;
